### ISSUE TITLE
Wrapper suppresses failed calls

### ISSUE THREAD

**Issue by deceze** [voryx/angular-wamp#12]
It looks like the wrappers around `.call()` etc. are not propagating failures; i.e. I can't write:

```javascript
$wamp.call('foo').then(angular.noop, function (err) { .. });
```

The `.then` error callback is never triggered.

**Comment by davidwdan** [comment]
@deceze I've made improvements to the error handling in the last commit.  There is still a little bit of work to be done before I tag a release, but it should fix the issue that you're experiencing.

**Comment by deceze** [comment]
So there's one central error event being emitted instead of being able to directly chain the call? That would greatly complicate the client side code I need to write, wouldn't it?

**Comment by davidwdan** [comment]
It does both. It emits an event and rejects the promise, which calls the error callback, so your code example should work.  Let me know if it works for you.

**Comment by deceze** [comment]
I see, great! Will give it a try and report back.

**Comment by deceze** [comment]
I've updated to `master` and it's working as it should now. :+1:
