### ISSUE TITLE
Can't access to $wamp.session

### ISSUE THREAD

**Issue by gereko3d** [voryx/angular-wamp#14]
Hi,
I'm having problem to access to $wamp.session after $wamp.open()
I know I'm connected with the WAMP router, I can check it from the router's log. But a 

```javascript
console.log($wamp.session) 
```
keeps returning null.
I also tried to inspect $wamp object, and I can't find any properties called session... Any suggestion?

**Comment by davidwdan** [comment]
Try `$wamp.connection.session`.   You can also listen to the `$wamp.open` event, which returns the session
```JS
    $scope.$on("$wamp.open", function (event, session) {
        console.log("the session", session); 
    });
```

**Comment by gereko3d** [comment]
Just found the and trying the second solution. It looks to work :D
Thanks!

On Wed, Mar 4, 2015 at 3:18 PM, David Dan <notifications@github.com> wrote:

> Try $wamp.connection.session. You can also listen to the $wamp.open
> event, which returns the session
>
>     $scope.$on("$wamp.open", function (event, session) {
>         console.log("the session", session);
>     });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voryx/angular-wamp/issues/14#issuecomment-77164964>.
>



-- 



*Francesco Cozzolino*
Settore Information Technology
Europe Consulting Coop. Soc.

Viale dell’Università, 11
Roma IT - 00185

Tel. 0647826364
Fax. 0649380240

f.cozzolino@europeconsulting.it
www.europeconsulting.it
