### ISSUE TITLE
authenticate after connection loss

### ISSUE THREAD

**Issue by blazsvigelj** [voryx/angular-wamp#16]
After connection loss new challenge is sent from server. Promise(onChallengeDeferred) should be reseted so I can resend authorization data from '$wamp.onchallenge' event callback. 

*One posible solution:*

    var onChallengeDeferred = $q.defer()

should be moved to function

    var onchallenge = function()  (session, method, extra) {
        var onChallengeDeferred = $q.defer() //added
        $rootScope.$broadcast ...

**Comment by davidwdan** [comment]
I'm not sure I understand.  `var onChallengeDeferred = $q.defer()` is already in the `onchallenge` function.

**Comment by blazsvigelj** [comment]
I'm sorry, I was looking at older version...

**Comment by davidwdan** [comment]
No problem. I was wondering if they was the case.
