### ISSUE TITLE
Subscribe On Scope

### ISSUE THREAD

**Issue by shanielh** [voryx/angular-wamp#17]
Hi.

Some (most) of the times when I subscribe to a topic, I want to unsubscribe it when the scope is destroyed.

I did a function that does it on my project, But it will be nice if it will be supported by `angular-wamp` :

    $wamp.subscribeOnScope = function(scope, channel, callback) {
      return $wamp.subscribe(channel, callback).then(function(subscription) {
        scope.$on('$destroy', function() {
          subscription.unsubscribe();
        });
      });
    };

b.t.w - If you want, I can pull request it :)

**Comment by davidwdan** [comment]
That's seems like a pretty good idea.  Let me think about it for a bit.

**Comment by DefunctExodus** [comment]
This would be something nice to have,  I know angular-socket io does it fairly well

**Comment by davidwdan** [comment]
This has been implemented

**Comment by shanielh** [comment]
Nice, Thanks
