### ISSUE TITLE
content-based publish/subscribe middleware

### ISSUE THREAD

**Issue by dhaowoods** [voryx/angular-wamp#18]
Is wamp fall into category of topic-based publish-subscribe middleware? how is different from content-based publish/subscribe middleware like [padres](http://msrg.utoronto.ca/projects/padres/index.php) and [IBM Gryphon](http://www.research.ibm.com/distributedmessaging/gryphon.html) ?

**Comment by davidwdan** [comment]
This is a good question for the WAMP discussion group.  https://groups.google.com/forum/#!forum/wampws

**Comment by dhaowoods** [comment]
thanks for pointing me to that group, :-D
