### ISSUE TITLE
autobahn.Session

### ISSUE THREAD

**Issue by xtrasmal** [voryx/angular-wamp#22]
Hi there,

How would I do something like this:

```javascript
var conn = new autobahn.Session('ws://localhost:8080',
        function() {
            console.warn('WebSocket connection open');
        },
        function() {
            console.warn('WebSocket connection closed');
        },
        {'skipSubprotocolCheck': true}
```

I've gotten this example from(http://socketo.me/docs/push).
It's implemented and it works. But now I'm trying to fit this in using angular-wamp.

Can you tell me how I get it working?

**Comment by davidwdan** [comment]
Angular-wamp only works with a WAMPv2 router. Your example looks like it's for v1.

**Comment by xtrasmal** [comment]
Yeah it is. So crap. :D I'm new to this world of autobahn and wamp..so didn't realise that I spend the whole weekend on the wrong shit.
