### ISSUE TITLE
Persistence between page loads

### ISSUE THREAD

**Issue by evildotstudios** [voryx/angular-wamp#23]
I am a newbie on this.

I can make the call with wamp and authenticate. But when I refresh the page I lose my session and will have to login again. This is probably a very basic issue, but comming from a PHP background, a lot is different here.

thank you

**Comment by davidwdan** [comment]
What type of authentication are you using?  

The basic idea is that you'd want to store a token client side (in local storage), that you use when you respond to the authentication challenge.

**Comment by evildotstudios** [comment]
it's a RPC call. can't seem to get my head around this. I don't see any obvious token from the server other from _id on $wamp.connection.session

**Comment by davidwdan** [comment]
You should authenticate the user when the WAMP connection is being established. https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#authentication

If you can give me some more info, I'll try to help.

What WAMP router are you using?
How are you authenticating the user on the server?
Are you prompting the user for a username/password or getting the login info from somewhere else?
