### ISSUE TITLE
Async initialization

### ISSUE THREAD

**Issue by bcamarneiro** [voryx/angular-wamp#26]
Is it possible to initialize the provider with async data? (If, for exmaple, I want the user to insert the address of the wamp router)

**Comment by davidwdan** [comment]
Take a look at https://github.com/voryx/angular-wamp/pull/25#issuecomment-102450684 

You can wrap `$wamp` with a new provider and inject the dependencies into it.  If you use a promise for your async operation, you'll call `wamp.open()` when the promise resolves.
