### ISSUE TITLE
WAMP-CRA

### ISSUE THREAD

**Issue by ppallesws** [voryx/angular-wamp#28]
This issue had me pulling my hair out.  I would recommend updating your docs to:

$scope.$on("$wamp.onchallenge", function (event, data) {
    if (data.method === "wampcra"){                
        return data.promise.resolve(autobahn.auth_cra.sign('someSecret', data.extra.challenge));
     } 
     //You can also access the following objects:
     // data.session             
     //data.extra
});

**Comment by davidwdan** [comment]
Thanks @ppallesws I'll update the README.

**Comment by ppallesws** [comment]
Absolutely.  Thank you for hard work on this.  Amazing job.
