### ISSUE TITLE
'session not open' error for subsequent connections 

### ISSUE THREAD

**Issue by jamesbrobb** [voryx/angular-wamp#31]
The app i'm working on only needs a socket connection for one specific part. Our current strategy is to only open a connection when it's required and then close the connection as soon as it's no longer needed.

This strategy worked using 0.0.4, but since updating (to any subsequent version), we've started to get a 'session not open' error when attempting to open any subsequent connections.

I've tracked this down to the fact that `sessionDeferred` and `sessionPromise` are instantiated within the scope of `$get`, but then never re-instantiated for subsequent connections. So once the first connection has been successfully opened, `connection.onopen` fires and `sessionDeferred` is resolved. As this controls the queuing action, when the next connection is opened, the queue no longer functions as expected and requests to all actions are immediately executed, before the connection is actually open.

**Comment by davidwdan** [comment]
Thanks, I merged your PR.
