### ISSUE TITLE
Publish latest 0.1.7 to npm

### ISSUE THREAD

**Issue by DanPurdy** [voryx/angular-wamp#42]
Would you be able to update npm to 0.1.7 please. The current version on there 0.1.5 doesn't include any source files.

Thanks!

<img width="476" alt="screen shot 2015-12-24 at 17 32 40" src="https://cloud.githubusercontent.com/assets/1386054/11996860/6482f7da-aa64-11e5-9f88-95c33e3257a7.png">

**Comment by davidwdan** [comment]
NPM is now up-to-date

**Comment by DanPurdy** [comment]
Thanks @davidwdan, much appreciated!
