### ISSUE TITLE
Any thoughts on Angular 2?

### ISSUE THREAD

**Issue by bradws** [voryx/angular-wamp#43]
Hi,

I have tried getting AutobahnJS v0.9.9 working with Angular 2, but cannot get it working in the Browser. If you're interested, please see my raised [github issue](https://github.com/angular/angular/issues/6447).

It seems silly, but it doesn't seem to recognize a second line of AutobahnJS code (it DOES recognize only 1 line !?!).

Anyway, are there any plans to implement angular-wamp using Angular 2 in the future? Do you have any thoughts on this and/or my issue?

Cheers,
bradws

**Comment by davidwdan** [comment]
@bradws I'm not sure about the autobahn issues, but we're working on a RxJS version, which will use observables, so you'll be able to use things like async pipes in Angular 2.  

The current version depends heavily on angular 1, so it won't be ported to angular 2.

**Comment by bradws** [comment]
Oh good to know. Will it be released on github? If so, what the approximate release date?
Thanks.

**Comment by davidwdan** [comment]
It'll be released on github, just don't have timeframe yet.

**Comment by bradws** [comment]
Again, good to know cheers. In the meantime, I'll take a quick look at [Wampy](https://github.com/KSDaemon/wampy.js) & [rx.wamp](https://github.com/paulpdaniels/rx.wamp)

**Comment by paulpdaniels** [comment]
@bradws rx.wamp is a little behind at the moment (Rx version is still at 2.3) let me know if you have any problems and I'll see if I can roll them into a fix/update.

**Comment by chiefmc** [comment]
@davidwdan Any progress on a RxJS-version of WAMP client?

**Comment by davidwdan** [comment]
@chiefmc yes, we have a version that we're using on our internal apps, but it needs more work before we can release it.

**Comment by chiefmc** [comment]
do you mind giving it us for a spin on a new project?

**Comment by creat-or** [comment]
any updates on this? :)

**Comment by darkbasic** [comment]
An update on the RxJS version?

**Comment by davidwdan** [comment]
I'll push it up when I get a chance

**Comment by davidwdan** [comment]
@darkbasic and @creat-or take a look https://github.com/voryx/thruway.js

**Comment by chiefmc** [comment]
Great! Thanks for this!
