### ISSUE TITLE
subscribeOnScope promise does not return subscription

### ISSUE THREAD

**Issue by kryo2k** [voryx/angular-wamp#47]
https://github.com/voryx/angular-wamp/blob/master/src/angular-wamp.js#L399-L401

Suggesting to add:
```js
return subscription;
```

Currently promise returns undefined.  I worked around this with an extension of that method.

Patched:

```js
subscribeOnScope: function (scope, channel, callback) {
    return this.subscribe(channel, callback).then(function (subscription) {
        scope.$on('$destroy', function () {
            return subscription.unsubscribe();
        });
        return subscription;
    });
},
```

**Comment by bondt** [comment]
@davidwdan Thanks!
@kryo2k Tested and works. Can you verify?

**Comment by davidwdan** [comment]
Fixed https://github.com/voryx/angular-wamp/pull/51
