### ISSUE TITLE
Reconnect after connection lost

### ISSUE THREAD

**Issue by creat-or** [voryx/angular-wamp#60]
To automatically reconnect after the connection is lost in autobahnjs, you have to return `false` in the onclose method, like:
```javascript
connection.onclose = function () {
   return false;
}
```
Unfortunately, I think there is no way to do this right now in angular-wamp, but I need it in my application. Is there another way, or could we implement it into the library?

**Comment by creat-or** [comment]
Hello guys,
I'd really need this feature, otherwise no automatic reconnect is possible. I could also write a PR, if you guide me :)

**Comment by davidwdan** [comment]
@creat-or looking through autobhanjs's docs and I can't find where it says that returning false will automatically reconnect.

**Comment by creat-or** [comment]
@davidwdan Yeah, it's hard to find. http://autobahn.ws/js/reference.html#connection-callbacks 

> "lost": The connection had been formerly established at least once, but now was lost. Automatic reconnection will happen **unless you return falsy** from this callback.

Funny enough it's unfortunately implemented in the exact opposite way. I tested it on another project (with autobahn.js without angular-wamp). Also at that time I found this solution in a comment, but I cannot find it right now.

**Comment by creat-or** [comment]
@davidwdan hello again, did you already have time to look into this?

**Comment by creat-or** [comment]
Hey @davidwdan I'm sorry... reconnect works as expected, I had an issue with my configuration. 🙈
