### ISSUE TITLE
error callback on subscribe failure is not getting called.

### ISSUE THREAD

**Issue by sachingorade** [voryx/angular-wamp#61]
Hi,
error function which we specify for subscribe function is not getting called. Success function is called if subscription is successful.
Following is my code,

```
$scope.subscription = $wamp.subscribe($scope.topic, function(args, kwargs, details){
	console.log(update);
}).then(
		function (subscription) {
			console.log('Success');
		},
		function (err) {
			console.log('Error' + err);
		}
);
```

I followed the snippet provided in Autobahn link - [http://autobahn.ws/js/reference.html#subscribe](http://autobahn.ws/js/reference.html#subscribe)

Is this the correct way to use error function or I am doing something wrong?

**Comment by sachingorade** [comment]
Any idea? what could be the reason?

**Comment by davidwdan** [comment]
@sachingorade that looks like it should work.  What kind of error are you expecting?  Aside from permissions, I can't think of too many times that that error handler would be called.

**Comment by sachingorade** [comment]
Error callback which I have provided in then() was not getting called. When I added following code in Subscribe function, now provided error callback is getting executed.

```
var p = connection.session.subscribe(topic, handler, options).then(
	function (s) {
		if (subscription.hasOwnProperty('id')) {
			delete subscription.id;
		}

		subscription = angular.extend(s, subscription);
		deferred.resolve(subscription);
		return s;
	},
        /*************************************
        * After adding following function, provided error callback is now getting executed.
        **************************************/
	function (err) { 
		deferred.reject(err);
	}
);
```

**Comment by davidwdan** [comment]
If you create a PR, I'll get it merged ASAP.

**Comment by sachingorade** [comment]
I have created a PR. Link for PR - [https://github.com/voryx/angular-wamp/pull/62](https://github.com/voryx/angular-wamp/pull/62)

**Comment by davidwdan** [comment]
@sachingorade I released a new version with this fix.
